[2024-08-24T10:42:26.640+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-24T10:42:26.655+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: report_shk_lost_emp.report_thefts manual__2024-08-24T10:41:23.423149+00:00 [queued]>
[2024-08-24T10:42:26.660+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: report_shk_lost_emp.report_thefts manual__2024-08-24T10:41:23.423149+00:00 [queued]>
[2024-08-24T10:42:26.660+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-24T10:42:26.668+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): report_thefts> on 2024-08-24 10:41:23.423149+00:00
[2024-08-24T10:42:26.673+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=284) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-24T10:42:26.674+0000] {standard_task_runner.py:63} INFO - Started process 286 to run task
[2024-08-24T10:42:26.675+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'report_shk_lost_emp', 'report_thefts', 'manual__2024-08-24T10:41:23.423149+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmpdm9douhx']
[2024-08-24T10:42:26.675+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask report_thefts
[2024-08-24T10:42:26.704+0000] {task_command.py:426} INFO - Running <TaskInstance: report_shk_lost_emp.report_thefts manual__2024-08-24T10:41:23.423149+00:00 [running]> on host 6d812cee5419
[2024-08-24T10:42:26.750+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Babanin' AIRFLOW_CTX_DAG_ID='report_shk_lost_emp' AIRFLOW_CTX_TASK_ID='report_thefts' AIRFLOW_CTX_EXECUTION_DATE='2024-08-24T10:41:23.423149+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-24T10:41:23.423149+00:00'
[2024-08-24T10:42:26.751+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-24T10:42:27.103+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-24T10:42:27.103+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_script.py", line 78, in main
    cursor.execute(f"CALL sync.{sync}(_src := '{df}')")
psycopg2.errors.UndefinedColumn: column s.sum_penalty does not exist
LINE 7:            s.sum_penalty,
                   ^
QUERY:  INSERT INTO report.shk_lost_emp AS shk_lost_emp(shk_id,
                                                    new_shk_id,
                                                    lostreason_id,
                                                    operation_dt)
    SELECT s.dt_date,
           s.wh_id,
           s.sum_penalty,
           s.sum_return
    FROM JSON_TO_RECORDSET(_src) AS s(dt_date       Bigint,
                                      wh_id         Bigint,
                                      lostreason_id Smallint,
                                      operation_dt  Date)
    ON CONFLICT (shk_id) DO UPDATE
    SET new_shk_id = EXCLUDED.new_shk_id,
        lostreason_id  = lostreason_id.sum_return,
        operation_dt  = EXCLUDED.operation_dt
CONTEXT:  PL/pgSQL function sync.shk_lost_emp(json) line 3 at SQL statement

[2024-08-24T10:42:27.110+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=report_shk_lost_emp, task_id=report_thefts, run_id=manual__2024-08-24T10:41:23.423149+00:00, execution_date=20240824T104123, start_date=20240824T104226, end_date=20240824T104227
[2024-08-24T10:42:27.118+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task report_thefts (column s.sum_penalty does not exist
LINE 7:            s.sum_penalty,
                   ^
QUERY:  INSERT INTO report.shk_lost_emp AS shk_lost_emp(shk_id,
                                                    new_shk_id,
                                                    lostreason_id,
                                                    operation_dt)
    SELECT s.dt_date,
           s.wh_id,
           s.sum_penalty,
           s.sum_return
    FROM JSON_TO_RECORDSET(_src) AS s(dt_date       Bigint,
                                      wh_id         Bigint,
                                      lostreason_id Smallint,
                                      operation_dt  Date)
    ON CONFLICT (shk_id) DO UPDATE
    SET new_shk_id = EXCLUDED.new_shk_id,
        lostreason_id  = lostreason_id.sum_return,
        operation_dt  = EXCLUDED.operation_dt
CONTEXT:  PL/pgSQL function sync.shk_lost_emp(json) line 3 at SQL statement
; 286)
[2024-08-24T10:42:27.128+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-24T10:42:27.137+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-24T10:42:27.139+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
